name: gradient_text_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: AnonymousPro
      fonts:
        - asset: assets/Anonymous_Pro/AnonymousPro-Bold.ttf
          weight: 700
        - asset: assets/Anonymous_Pro/AnonymousPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/Anonymous_Pro/AnonymousPro-Italic.ttf
          style: italic
        - asset: assets/Anonymous_Pro/AnonymousPro-Regular.ttf
